const INITIAL_ADS = [
  {
    id: "ad-1",
    title: "Бездротові навушники Sony WH-1000XM4 Black (повний комплект)",
    category: "Електроніка",
    price: 7900,
    negotiable: true,
    condition: "Відмінний",
    city: "Київ",
    district: "Подільський р-н",
    createdAt: "2026-10-06T17:30:00.000Z",
    sellerName: "Олександр Коваленко",
    phone: "+380 67 123 45 67",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80",
    description: `Продаю флагманські навушники Sony WH-1000XM4 у класичному чорному кольорі. Легендарне активне шумозаглушення (ANC), висока автономність та чистий, деталізований звук із глибоким басом.\n\n• Стан: Відмінний (9/10), використовувалися акуратно, переважно вдома для роботи за ноутбуком.\n• Батарея: Тримає заряд до 30 годин із увімкненим шумозаглушенням (як нові).\n• Комплект: Навушники, оригінальний жорсткий чохол, кабель Type-C, AUX 3.5мм, літаковий перехідник, рідна коробка.\n\nСамовивіз або безпечна OLX Доставка.`
  },
  {
    id: "ad-2",
    title: "Apple iPhone 15 Pro 128GB Natural Titanium (Ідеал, 98% АКБ)",
    category: "Електроніка",
    price: 33500,
    negotiable: false,
    condition: "Ідеальний",
    city: "Львів",
    district: "Франківський р-н",
    createdAt: "2026-10-06T15:10:00.000Z",
    sellerName: "Максим Демчук",
    phone: "+380 93 456 78 90",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80",
    description: `Телефон у стані нового, з першого дня носив у захисному чохлі Spigen і під якісним склом.\n\n• Акумулятор: 98% залишкової ємності.\n• Neverlock — працює з усіма фізичними SIM та eSIM по всьому світу.\n• Без жодних падінь і ремонтів, дисплей та титан без подряпин.\n• Повний комплект: коробка, рідний плетений кабель Type-C, чек із магазину.`
  },
  {
    id: "ad-3",
    title: "Ноутбук Apple MacBook Pro 14 M2 Pro 16/512GB Space Gray",
    category: "Електроніка",
    price: 59900,
    negotiable: true,
    condition: "Ідеальний",
    city: "Київ",
    district: "Шевченківський р-н",
    createdAt: "2026-10-06T13:45:00.000Z",
    sellerName: "Тарас",
    phone: "+380 50 111 22 33",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80",
    description: `Потужний робочий ноутбук для монтажу відео, програмування та графіки.\n\n• Процесор: Apple M2 Pro (10 ядер CPU / 16 ядер GPU)\n• ОЗП: 16 GB уніфікованої пам'яті\n• SSD: 512 GB надшвидкий накопичувач\n• Екран: Liquid Retina XDR 120Hz Promotion\n• Батарея: 54 цикли, 99% здоров'я\n• Комплект: Ноутбук, оригінальний блок 67W, MagSafe 3 кабель, коробка.`
  },
  {
    id: "ad-4",
    title: "Volkswagen Golf 7 2016 1.6 TDI Дизель Автомат DSG 7",
    category: "Авто",
    price: 385000,
    negotiable: true,
    condition: "Відмінний",
    city: "Львів",
    district: "Сихівський р-н",
    createdAt: "2026-10-06T11:20:00.000Z",
    sellerName: "Володимир",
    phone: "+380 67 999 44 22",
    deliveryOlx: false,
    deliveryNovaPoshta: false,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&auto=format&fit=crop&q=80",
    description: `Свіжопригнаний з Німеччини, повністю розмитнений та поставлений на український облік.\n\n• Пробіг: 184 000 км (рідний, є сервісна книга з офіційного дилера VW)\n• Двигун: 1.6 TDI (економічний, витрата по трасі 4.2 л / 100 км)\n• Коробка: 7-ступеневий автомат DSG, перемикає м'яко без ривків\n• Комплектація: адаптивний круїз-контроль, двозонний клімат, парктроніки по колу, сенсорний дисплей, мультикермо.\n• Замінено комплект ГРМ та мастило 2 тис. км тому. Готовий до будь-яких перевірок на вашому СТО.`
  },
  {
    id: "ad-5",
    title: "1-кімнатна квартира 46 м² з панорамними вікнами (ЖК біля Позняків)",
    category: "Нерухомість",
    price: 16000,
    negotiable: false,
    condition: "Ідеальний",
    city: "Київ",
    district: "Дарницький р-н",
    createdAt: "2026-10-06T09:15:00.000Z",
    sellerName: "Олена Рієлтор",
    phone: "+380 98 333 11 00",
    deliveryOlx: false,
    deliveryNovaPoshta: false,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80",
    description: `Довгострокова оренда затишної сучасної квартири у новому будинку.\n\n• Площа: 46 м², поверх 14/25, є підземний паркінг та укриття у будинку.\n• Метро «Позняки» — 7 хвилин пішки.\n• Меблі та техніка: двоспальне ліжко з ортопедичним матрацом, smart-TV 55\", посудомийна машина Bosch, бойлер, інверторний кондиціонер, духовка.\n• Територія під охороною 24/7, відеонагляд, консьєрж.\n• Без домашніх тварин.`
  },
  {
    id: "ad-6",
    title: "Електросамокат Xiaomi Mi Electric Scooter Pro 2 Black",
    category: "Хобі та спорт",
    price: 13500,
    negotiable: true,
    condition: "Відмінний",
    city: "Одеса",
    district: "Приморський р-н",
    createdAt: "2026-10-05T19:30:00.000Z",
    sellerName: "Богдан",
    phone: "+380 63 777 22 55",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&auto=format&fit=crop&q=80",
    description: `Швидкий та надійний міський електросамокат у відмінному стані.\n\n• Запас ходу: до 45 км на одному заряді\n• Максимальна швидкість: 25 км/год (3 режими швидкості: Eco, Drive, Sport)\n• Потужність двигуна: 600W у піку, легко долає гірки до 20°\n• Пробіг всього 430 км за літо, батарея тримає заряд на 100%\n• У комплекті оригінальна зарядка та запасна покришка з камерою.`
  },
  {
    id: "ad-7",
    title: "PlayStation 5 Digital Edition + 2 геймпади DualSense + зарядна станція",
    category: "Електроніка",
    price: 16900,
    negotiable: false,
    condition: "Ідеальний",
    city: "Харків",
    district: "Шевченківський р-н",
    createdAt: "2026-10-05T16:40:00.000Z",
    sellerName: "Артем Мельник",
    phone: "+380 68 222 33 44",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80",
    description: `Консоль купувалася для проходження ексклюзивів, стан як з магазину.\n\n• Працює безшумно, 3-я ревізія (CFI-1200), не перегрівається.\n• 2 оригінальні білі геймпади DualSense (стіки перевірені, без дрифту).\n• Фірмова подвійна док-станція Sony для зручної зарядки геймпадів.\n• Повний набір дротів: HDMI 2.1, живлення, коробка, гарантійний талон.`
  },
  {
    id: "ad-8",
    title: "Інверторний генератор 2.0 кВт MaXpeedingRods безшумний",
    category: "Дім і сад",
    price: 18500,
    negotiable: true,
    condition: "Новий",
    city: "Дніпро",
    district: "Соборний р-н",
    createdAt: "2026-10-05T14:10:00.000Z",
    sellerName: "Сергій Бондар",
    phone: "+380 50 654 32 10",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80",
    description: `Сучасний компактний бензиновий інверторний генератор із чистою синусоїдою (безпечний для котлів, ноутбуків та чутливої електроніки).\n\n• Номінальна потужність: 1.8 кВт, максимальна: 2.0 кВт.\n• Тихий режим роботи (Eco mode, рівень шуму лише 58 дБ на відстані 7м).\n• Вага всього 18.5 кг — легко переносити однією рукою.\n• Витрата пального: 0.5-0.7 л/год залежно від навантаження.\n• Новий у коробці, перевірений, залито стартове мастило Motul.`
  },
  {
    id: "ad-9",
    title: "Оригінальні кросівки Nike Air Jordan 1 Low Black/White (43 розмір)",
    category: "Мода і стиль",
    price: 3600,
    negotiable: true,
    condition: "Новий",
    city: "Дніпро",
    district: "Центральний р-н",
    createdAt: "2026-10-05T11:00:00.000Z",
    sellerName: "Ірина",
    phone: "+380 97 777 99 11",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80",
    description: `Оригінальні кросівки Nike Air Jordan 1 Low у класичному монохромному забарвленні.\n\n• Замовлялися з офіційного європейського сайту Nike, не підійшов розмір.\n• Розмір: EU 43 / US 9.5 (довжина устілки 27.5 см).\n• Натуральна шкіра, дуже якісна прошивка підошви.\n• Усі заводські бірки на місці, коробка у відмінному стані. Відправлю з приміркою через OLX Доставку!`
  },
  {
    id: "ad-10",
    title: "Цуценя французького бульдога (хлопчик, палевий окрас, щеплений)",
    category: "Тварини",
    price: 12000,
    negotiable: true,
    condition: "Новий",
    city: "Вінниця",
    district: "Вишенька",
    createdAt: "2026-10-04T16:30:00.000Z",
    sellerName: "Наталія",
    phone: "+380 96 444 88 12",
    deliveryOlx: false,
    deliveryNovaPoshta: false,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&auto=format&fit=crop&q=80",
    description: `Чарівний, життєрадісний хлопчик породи Французький бульдог шукає люблячу родину!\n\n• Вік: 2.5 місяці, правильна анатомія, гарна породна голова та широкі груди.\n• Проглистований, зроблені всі перші щеплення за віком, має міжнародний ветеринарний паспорт.\n• Їсть корм супер-преміум класу, активний, привчений до пелюшки.\n• Батьки чистокровні, з документами КСУ, без генетичних захворювань дихальних шляхів.\n• Можлива доставка по області або особиста зустріч.`
  },
  {
    id: "ad-11",
    title: "Дитяча універсальна коляска 2в1 Anex m/type Black Leather",
    category: "Дитячий світ",
    price: 15400,
    negotiable: true,
    condition: "Відмінний",
    city: "Львів",
    district: "Франківський р-н",
    createdAt: "2026-10-04T12:00:00.000Z",
    sellerName: "Христина",
    phone: "+380 67 333 55 66",
    deliveryOlx: false,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800&auto=format&fit=crop&q=80",
    description: `Стильна та маневрена коляска преміум-класу Anex m/type з екошкіри чорного кольору.\n\n• Люлька простора, ортопедичний матрацик, вентильоване дно.\n• Прогулянковий блок реверсивний (обличчям до мами або до світу), спинка розкладається в горизонтальне положення.\n• Потрійна амортизація та безкамерні колеса, які не бояться проколів.\n• Комплектація: люлька, прогулянка, рюкзак для мами, дощовик, москітна сітка, накидка на ніжки.\n• Стан текстилю та рами відмінний, після однієї дитини.`
  },
  {
    id: "ad-12",
    title: "Кавомашина зернова DeLonghi Magnifica S з ручним капучинатором",
    category: "Дім і сад",
    price: 8900,
    negotiable: true,
    condition: "Відмінний",
    city: "Київ",
    district: "Оболонський р-н",
    createdAt: "2026-10-03T18:00:00.000Z",
    sellerName: "Сергій Поліщук",
    phone: "+380 63 999 88 77",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80",
    description: `Надійна та невибаглива італійська зернова кавоварка DeLonghi Magnifica S.\n\n• Готує смачний насичений еспресо та класичне американо в один дотик.\n• Парове сопло Panarello збиває густу стійку пінку для капучино чи лате.\n• Пройшла сервісне обслуговування: повне очищення від накипу (декальцинація) та змащення заварювального блоку якісним харчовим силіконом.\n• Працює як із зерновою, так і з меленою кавою. Жодних нарікань!`
  }
];

// Генератор випадкових/креативних товарів для автозаповнення
const RANDOM_PRODUCTS_POOL = [
  {
    title: "Дзеркальний фотоапарат Sony A7 III Body + 2 акумулятори",
    category: "Електроніка",
    price: 43500,
    negotiable: true,
    condition: "Відмінний",
    city: "Київ",
    district: "Голосіївський р-н",
    sellerName: "Євген Фотограф",
    phone: "+380 67 555 12 34",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80",
    description: "Професійна повнокадрова бездзеркальна камера Sony A7 III. Пробіг затвора 32 000 кадрів. Матриця чиста, без пилу та битих пікселів. У комплекті 2 оригінальні батареї NP-FZ100, швидкий зарядний пристрій, ремінь та коробка."
  },
  {
    title: "Гірський велосипед Trek Marlin 7 Gen 3 (29 колеса, гідравліка)",
    category: "Хобі та спорт",
    price: 24500,
    negotiable: true,
    condition: "Відмінний",
    city: "Харків",
    district: "Шевченківський р-н",
    sellerName: "Дмитро Вело",
    phone: "+380 50 888 12 34",
    deliveryOlx: false,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&auto=format&fit=crop&q=80",
    description: "Надійний трейловий хардтейл Trek Marlin 7. Розмір рами L (на зріст 175-188 см). Трансмісія 1x10 Shimano Deore з муфтою Shadow Plus. Гідравлічні дискові гальма. Пройшов повне ТО."
  },
  {
    title: "Робот-пилосос Roborock S8 Pro Ultra з базою самоочищення",
    category: "Дім і сад",
    price: 27900,
    negotiable: true,
    condition: "Ідеальний",
    city: "Одеса",
    district: "Таїрова",
    sellerName: "Анастасія",
    phone: "+380 93 111 44 77",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80",
    description: "Топовий робот-пилосос для вологого та сухого прибирання з багатофункціональною станцією RockDock Ultra. Сам миє ганчірку гарячою водою, сушить гарячим повітрям та скидає сміття в мішок. Стан нового."
  },
  {
    title: "Шкіряна чоловіча куртка косуха Zara Man (Розмір L, чорна)",
    category: "Мода і стиль",
    price: 2200,
    negotiable: true,
    condition: "Ідеальний",
    city: "Київ",
    district: "Печерський р-н",
    sellerName: "Ярослав",
    phone: "+380 66 321 98 76",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80",
    description: "Стильна байкерська куртка Zara з м'якої якісної екошкіри. Одягалася кілька разів, без потертостей та заломів. Вся металева фурнітура (блискавки, кнопки) працює справно. Підкладка чиста."
  },
  {
    title: "Смарт-годинник Apple Watch Series 9 45mm Midnight Aluminum",
    category: "Електроніка",
    price: 13900,
    negotiable: false,
    condition: "Відмінний",
    city: "Дніпро",
    district: "Перемога",
    sellerName: "Олег",
    phone: "+380 68 765 43 21",
    deliveryOlx: true,
    deliveryNovaPoshta: true,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80",
    description: "Оригінальний смарт-годинник Apple Watch 9 45мм. Новий процесор S9 SiP, функція жесту Double Tap, яскравий Always-On екран до 2000 ніт. Батарея 96%. Рідний магнітний зарядний кабель та силіконовий ремінець S/M."
  },
  {
    title: "BMW 320i F30 M-Sport 2017 Автомат 2.0 TwinPower Turbo",
    category: "Авто",
    price: 610000,
    negotiable: true,
    condition: "Відмінний",
    city: "Київ",
    district: "Оболонь",
    sellerName: "Денис",
    phone: "+380 67 888 00 11",
    deliveryOlx: false,
    deliveryNovaPoshta: false,
    deliveryMeet: true,
    image: "https://images.unsplash.com/photo-1555353540-64580b51c258?w=800&auto=format&fit=crop&q=80",
    description: "Оригінальний заводський M-пакет: обвіс, M-кермо, сидіння Alcantara з бічною підтримкою, чорна стеля. Пробіг 118 000 км. Обслуговування на спеціалізованому сервісі BMW, заміна мастила кожні 7-8 тис. км. Без ДТП."
  }
];
